:: Hard reset the HEAD: git push origin +<NEW_HEAD_COMMIT_HASH>:master
:: 6af74344a888bdf9fbb35d887c3f77691820a50e
:: git push origin +6af74344a888bdf9fbb35d887c3f77691820a50e:master
:: cd /e
:: cd Documents/Lua-Projs/SVN/TrackAssemblyTool_GIT_master

@echo off

set workpubRev=%~dp0
set workpubBin=F:\Games\Steam\steamapps\common\GarrysMod\bin
set workpubName=TrackAssembly
set workpubID=287012681
set workpubDirs=(lua)

title Addon %workpubName% updater/publisher

echo Press Crtl+C to terminate !
echo Press a key if you do not want to wait !
echo Rinning in %workpubRev%.
echo Npp Find --\h{1,}\n-- replace --\n-- in dos format before commit !
echo.

timeout 3
rd /S /Q %workpubRev%Workshop
md %workpubRev%Workshop\%workpubName%
for %%i in %workpubDirs% do (
  echo Extracting %%i
  timeout 3
  xcopy %workpubRev%%%i %workpubRev%Workshop\%workpubName%\%%i /EXCLUDE:%workpubRev%data\workshop\key.txt /E /C /I /F /R /Y
)
copy %workpubRev%data\workshop\addon.json %workpubRev%Workshop\%workpubName%\addon.json
call %workpubBin%\gmad.exe create -folder "%workpubRev%Workshop\%workpubName%" -out "%workpubRev%Workshop\%workpubName%.gma"

timeout 15

IF DEFINED workpubID (
  call %workpubBin%\gmpublish.exe update -addon "%workpubRev%Workshop\%workpubName%.gma" -id "%workpubID%" -icon "%workpubRev%data\pictures\icon.jpg" -changes "Generated by Batch!"
) ELSE (
  call %workpubBin%\gmpublish.exe create -addon "%workpubRev%Workshop\%workpubName%.gma" -icon "%workpubRev%data\pictures\icon.jpg"
)

echo.
echo %workpubName% Published !
echo.
timeout 500
exit
